-- Add pick/drop GPS locations
ALTER TABLE skip_job_completion
  ADD COLUMN IF NOT EXISTS pick_lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS pick_lng DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS drop_lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS drop_lng DOUBLE PRECISION;
